language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.2
branches:
  only:
    - master
env:
  global:
  - secure: "J2/UOjDgJNI9qZ0sEQUKDb3iLctyvsAPb3s+pSxDF0FVG5nPx3kDUU0p5yYzr7xcvxlpWCVyjKOYJdA7eM9mupml1muwOH5adcU0nIxBtd8zshRw8SIvyUpjL1q7CeABHyi2QpbvwbYLE8bRngWMk3SqRHrqLEIFUb6mpyfZsy8=" 

